### ISSUE TITLE
Can't substitute subclass for superclass in ComponentDict

### ISSUE THREAD

**Issue by markiragoldberg** [HexDecimal/python-tcod-ec#2]
I am using your tcod tutorial code. I want to add a ComponentDict to the Item class to store optional components like Consumable, Equippable, and probably others later.

But in the existing code, I can't do things like:
`confusion_scroll.comps[Consumable] = ConfusionConsumable()`
because tcod-ec raises a TypeError, even though a ConfusionConsumable is a Consumable.

Shouldn't this be possible?

**Comment by HexDecimal** [comment]
For a moment I supported this with the [abstract_component](https://python-tcod-ec.readthedocs.io/en/latest/api.html#tcod.ec.abstract_component) decorator, but after a while it seemed like it might be a better option to create a class which contains the type which can be derived instead of having this exception to how types are handled.

So right now this is the current way I'd handle this situation:
```py
class Base:
    pass
class Derived:
   pass
@attrs.define
class Abstract:
   value: Base

entity = tcod.ec.ComponentDict()
entity[Abstract] = Abstract(Derived())
```

[Composite](https://python-tcod-ec.readthedocs.io/en/latest/api.html#tcod.ec.Composite) handles derived classes, classes with multiple parents, and allows multiples of the same component type, but it makes the simple cases harder to use.

Mixing these two types might be better than using Composite alone:
```py
class Base:
    pass
class Derived:
   pass

entity = tcod.ec.ComponentDict([tcod.ec.Composite])
entity[Composite][Base] = (Derived(),)
(derived,) = entity[Composite][Base]
```

**Comment by markiragoldberg** [comment]
I don't understand why disallowing the substitution is desirable, and these approaches prevent reusing a lot more of the tutorial code. So I'm not going to use tcod-ec for this project.

**Comment by HexDecimal** [comment]
I'm sorry if I didn't explain it well.  The main issue comes from the ambiguous methods of adding a component such as. `ComponentDict(components)` and `ComponentDict.set(component)`.  If you have `Derived` then when you pass it to one of these functions how does it get resolved to `Base`?  I came up with the `abstract_component` decorator which is still in the API:
```py
@abstract_component
class Base:
    pass

class Derived(Base):
    pass

entity = ComponentDict([Derived()])
entity[Base] = Derived()
entity.set(Derived())
```
This only works for a very narrow case however.  I was also worried that it was too much of a hack.  To resolve this I made `Composite` which can handle every edge-case, but that class itself is harder to use than `ComponentDict`.

ECS is based around small components so I assumed that making a new small component to resolve abstract type variables would be the better option than `abstract_component`.  This was always enough for my needs, especially after I found I could add `Composite` as a component to `ComponentDict`, but I never had feedback on this until now.

Is `Composite` to complex to consider for your case, or would you rather just use `abstract_component`?
